version: '3.4'
services:
  fornecedor-service:
    image: fornecedor-service
    depends_on:
      - kafka
      - zookeeper
    restart: always
    build:
      context: ./fornecedor-service
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8084:8084"
    command: mvn spring-boot:run
    networks:
      - udemy-network
  produto-service:
    image: produto-service
    depends_on:
      - kafka
      - zookeeper
    restart: always
    build:
      context: ./produto-service
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8083:8083"
    command: mvn spring-boot:run
    networks:
      - udemy-network
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
networks:
  udemy-network:
    driver: bridge
